project:
  type: website

website:
  title: "Wenwei Wu's Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: dark
    css: styles.css
    toc: true

